<?php

/**
 * Implements hook_js_alter()
 */
function custom_library_versioner_js_alter(&$variables): void {
  /** @var \Drupal\custom_library_versioner\CustomLibraryVersionerHelper $helper */
  $helper = \Drupal::service('custom_library_versioner.helper');
  $helper->setVersion($variables);
}

/**
 * Implements hook_css_alter()
 */
function custom_library_versioner_css_alter(&$variables): void {
  /** @var \Drupal\custom_library_versioner\CustomLibraryVersionerHelper $helper */
  $helper = \Drupal::service('custom_library_versioner.helper');
  $helper->setVersion($variables);
}
